# Generated by Django 6.0 on 2026-01-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash on delivery', 'Cash on Delivery'), ('upi', 'UPI'), ('card', 'Card')], max_length=20),
        ),
    ]
